[package]
name = "wayland_protocol_code_generator"
version = "0.1.0"
authors = ["Yang Keao <keao.yang@yahoo.com>"]
edition = "2018"

[dependencies]
wayland_protocol_scanner = {path = "../wayland_protocol_scanner"}
heck = "0.3.1"

[lib]
proc-macro = true
